"""
Shared configuration for the InteractingMaps pipeline (evaluation.py, demo.py).

Contents
--------
- DATASET_SEGMENTS : per-dataset lists of hand-picked constant-ω segments
  (produced by find_segments.py). Each segment carries t_start, frame_duration,
  n_frames, initial_R and sensor_size.
- DATASET_CONFIGS  : {dataset: segments[0]} convenience (first segment per set).
- THESIS_PARAMS / COOK_PARAMS : per-relation relaxation step sizes (delta_*)
  for the two networks; THESIS_PARAMS also carries delta_IMU (the R-anchor
  strength, reused by the CMax variants).
- ITERS_PER_FRAME  : inner message-passing iterations per frame.
- Path/helper functions (get_dataset_paths, get_initial_R_from_imu).

Edit this file to add datasets or change hyper-parameters. Segment blocks are
generated by find_segments.py.
"""

import os
import numpy as np

# ---------------------------------------------------------------------------
# Dataset Configurations (from find_segments.py)
# ---------------------------------------------------------------------------
DATASET_SEGMENTS = {
    # =======================================================================
    # Regenerated by the reworked find_segments.py (growth search).
    #
    # 'duration' = the VALIDATED interval over which omega stays quasi-constant.
    # 'n_frames' = a hyperparameter, capped so n_frames*frame_duration never
    # exceeds 'duration'. evaluation.segment_n_frames() enforces this.
    #
    # Earlier configs carried n_frames=150 (3.0 s) for every segment regardless
    # of the validated duration, i.e. segments were run 2-6x longer than omega
    # was actually constant. Real constant-omega windows are 0.35-1.3 s on the
    # RPG sets and 2.4 s on ECRot.
    # =======================================================================
    'boxes_rotation': [
    {  # quality=1.04, |w|=1.810 rad/s, dominant=w_z, rel_std=0.187
        'id': 'seg_A', 't_start': 9.972, 'duration': 0.50,
        'frame_duration': 0.02, 'n_frames': 25,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.60, |w|=1.091 rad/s, dominant=w_x, rel_std=0.227
        'id': 'seg_B', 't_start': 7.272, 'duration': 0.50,
        'frame_duration': 0.02, 'n_frames': 25,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.45, |w|=0.750 rad/s, dominant=w_y, rel_std=0.233
        'id': 'seg_C', 't_start': 4.322, 'duration': 0.60,
        'frame_duration': 0.02, 'n_frames': 30,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.33, |w|=0.526 rad/s, dominant=w_y, rel_std=0.247
        'id': 'seg_D', 't_start': 1.972, 'duration': 0.70,
        'frame_duration': 0.02, 'n_frames': 35,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.21, |w|=0.352 rad/s, dominant=w_y, rel_std=0.242
        'id': 'seg_E', 't_start': 0.472, 'duration': 0.60,
        'frame_duration': 0.02, 'n_frames': 30,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    ],

    # Secondary dataset: these segments needed threshold relaxation
    # (rel_std up to 0.46 vs ~0.22 elsewhere), so they are measurably lower
    # quality. Included for completeness; kept OUT of the headline table.
    'shapes_rotation': [
    {  # quality=1.20, |w|=1.616 rad/s, dominant=w_z, rel_std=0.276
        'id': 'seg_A', 't_start': 9.641, 'duration': 1.05,
        'frame_duration': 0.02, 'n_frames': 52,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.83, |w|=1.897 rad/s, dominant=w_x, rel_std=0.256
        'id': 'seg_B', 't_start': 20.766, 'duration': 0.35,
        'frame_duration': 0.02, 'n_frames': 17,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.66, |w|=1.143 rad/s, dominant=w_z, rel_std=0.144
        'id': 'seg_C', 't_start': 8.066, 'duration': 0.45,
        'frame_duration': 0.02, 'n_frames': 22,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.49, |w|=0.882 rad/s, dominant=w_x, rel_std=0.353
        'id': 'seg_D', 't_start': 5.316, 'duration': 0.75,
        'frame_duration': 0.02, 'n_frames': 37,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.44, |w|=0.669 rad/s, dominant=w_y, rel_std=0.279
        'id': 'seg_E', 't_start': 2.291, 'duration': 0.85,
        'frame_duration': 0.02, 'n_frames': 42,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    ],

    'poster_rotation': [
    {  # quality=1.67, |w|=2.565 rad/s, dominant=w_z, rel_std=0.221
        'id': 'seg_A', 't_start': 14.116, 'duration': 0.70,
        'frame_duration': 0.02, 'n_frames': 35,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=1.28, |w|=1.774 rad/s, dominant=w_z, rel_std=0.237
        'id': 'seg_B', 't_start': 12.066, 'duration': 0.90,
        'frame_duration': 0.02, 'n_frames': 44,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.70, |w|=0.997 rad/s, dominant=w_x, rel_std=0.212
        'id': 'seg_C', 't_start': 8.766, 'duration': 0.80,
        'frame_duration': 0.02, 'n_frames': 39,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.47, |w|=0.522 rad/s, dominant=w_y, rel_std=0.205
        'id': 'seg_D', 't_start': 4.666, 'duration': 1.30,
        'frame_duration': 0.02, 'n_frames': 65,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.45, |w|=0.597 rad/s, dominant=w_y, rel_std=0.240
        'id': 'seg_E', 't_start': 1.666, 'duration': 1.00,
        'frame_duration': 0.02, 'n_frames': 49,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    ],

    'dynamic_rotation': [
    {  # quality=1.64, |w|=2.498 rad/s, dominant=w_z, rel_std=0.153
        'id': 'seg_A', 't_start': 11.719, 'duration': 0.60,
        'frame_duration': 0.02, 'n_frames': 30,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=1.60, |w|=2.743 rad/s, dominant=w_z, rel_std=0.174
        'id': 'seg_B', 't_start': 24.719, 'duration': 0.50,
        'frame_duration': 0.02, 'n_frames': 25,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=1.51, |w|=2.761 rad/s, dominant=w_z, rel_std=0.228
        'id': 'seg_C', 't_start': 26.469, 'duration': 0.50,
        'frame_duration': 0.02, 'n_frames': 25,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.81, |w|=1.363 rad/s, dominant=w_z, rel_std=0.230
        'id': 'seg_D', 't_start': 10.119, 'duration': 0.60,
        'frame_duration': 0.02, 'n_frames': 30,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    {  # quality=0.78, |w|=1.439 rad/s, dominant=w_y, rel_std=0.232
        'id': 'seg_E', 't_start': 31.869, 'duration': 0.50,
        'frame_duration': 0.02, 'n_frames': 25,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    ],

    # --- ECRot synthetic (tub-rip/ECRot), converted by convert_ecrot.py -------
    # CLEAN direct-omega ground truth: omega_gt.txt comes from the bag's
    # /cam0/twist topic, so scoring needs no quaternion differencing.
    # NOTE: City and Street share the SAME camera trajectory (ECRot renders one
    # motion through different scenes), so their omega_gt.txt -- and therefore
    # their segments -- are identical by design. Only events.txt (scene) and
    # imu.txt (independent noise realisation) differ. That makes the pair a
    # controlled scene-content ablation at fixed motion.
    # Dense scenes (~280k events/frame) -> the CMax variants are slow here.
    'ecrot_city': [
    {  # quality=1.80, |w|=1.323 rad/s, dominant=w_y, rel_std=0.120
        'id': 'seg_A', 't_start': 2.551, 'duration': 2.40,
        'frame_duration': 0.02, 'n_frames': 120,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    ],
    'ecrot_street': [
    {  # quality=1.80, |w|=1.323 rad/s, dominant=w_y, rel_std=0.120
        'id': 'seg_A', 't_start': 2.551, 'duration': 2.40,
        'frame_duration': 0.02, 'n_frames': 120,
        'initial_R': None, 'sensor_size': (180, 240),
    },
    ],
}

# Backward-compatible: single config = first segment per dataset
DATASET_CONFIGS = {
    name: segs[0] for name, segs in DATASET_SEGMENTS.items()
}

THESIS_PARAMS = dict(
    delta_VFG=0.12,    # OFCE, 0.15
    delta_IG=0.10,     # G from I: moderate
    delta_GI=0.05,     # I from G: gentle (Poisson step, needs stability)
    delta_RF=0.05,     # F from R: WEAK (let OFCE build local structure) 0.03
    delta_FR=0.50,     # R from F: strong (global aggregate, stable)  0.50
    delta_IMU=0.30     
)

COOK_PARAMS = dict(
    delta_VFG=0.08,
    delta_IG=0.12,
    delta_GI=0.08,
    delta_RF=0.03,  #0.10
    delta_FR=0.30,   #0.10,
)

ITERS_PER_FRAME = 75   # Thesis use 50-75; 

# Distortion handling (ablation switch):
#   'undistort_events' : undistort events before binning; pinhole C    (original)
#   'C_full'           : raw events; distortion-aware coords + Jacobian in C  (best)
DISTORTION_MODE = 'C_full'

# ---------------------------------------------------------------------------
# Helper: resolve paths for a dataset
# ---------------------------------------------------------------------------

def get_dataset_paths(dataset_name: str, base_dir: str = None):
    """Return a dict with all file paths for a given dataset."""
    if base_dir is None:
        base_dir = os.path.join(os.path.dirname(__file__), 'data')

    data_dir = os.path.join(base_dir, dataset_name)
    return {
        'data_dir': data_dir,
        'events': os.path.join(data_dir, 'events.txt'),
        'calib': os.path.join(data_dir, 'calib.txt'),
        'imu': os.path.join(data_dir, 'imu.txt'),
        'groundtruth': os.path.join(data_dir, 'groundtruth.txt'),
        'omega_gt': os.path.join(data_dir, 'omega_gt.txt'),   # clean direct ω (ECRot)
        'images': os.path.join(data_dir, 'images.txt'),

    }

def get_initial_R_from_imu(dataset_name: str):
    """Read the IMU gyroscope at t_start to get the correct initial_R."""
    cfg = DATASET_CONFIGS[dataset_name]
    paths = get_dataset_paths(dataset_name)
    
    imu_data = np.loadtxt(paths['imu'], dtype=np.float64)
    t_start = cfg['t_start']
    dt = cfg['frame_duration']
    
    # Find IMU readings closest to t_start
    t_lo = t_start
    t_hi = t_start + dt
    mask = (imu_data[:, 0] >= t_lo) & (imu_data[:, 0] < t_hi)
    
    if np.sum(mask) > 0:
        omega = np.mean(imu_data[mask, 4:7], axis=0)
    else:
        idx = np.argmin(np.abs(imu_data[:, 0] - t_start))
        omega = imu_data[idx, 4:7]
    
    return omega * dt  # rad/s → rad/frame