"""
Shared configuration for the InteractingMaps pipeline (evaluation.py, demo.py).

Contents
--------
- DATASET_SEGMENTS : per-dataset lists of hand-picked constant-ω segments
  (produced by find_segments.py). Each segment carries t_start, frame_duration,
  n_frames, initial_R and sensor_size.
- DATASET_CONFIGS  : {dataset: segments[0]} convenience (first segment per set).
- THESIS_PARAMS / COOK_PARAMS : per-relation relaxation step sizes (delta_*)
  for the two networks; THESIS_PARAMS also carries delta_IMU (the R-anchor
  strength, reused by the CMax variants).
- ITERS_PER_FRAME  : inner message-passing iterations per frame.
- Path/helper functions (get_dataset_paths, get_initial_R_from_imu).

Edit this file to add datasets or change hyper-parameters. Segment blocks are
generated by find_segments.py.
"""

import os
import numpy as np

# ---------------------------------------------------------------------------
# Dataset Configurations (from find_segments.py)
# ---------------------------------------------------------------------------
DATASET_SEGMENTS = {
    'boxes_rotation': [
    {  # quality=1.47, |ω|=1.810 rad/s, dominant=ω_z
        'id': 'seg_A',
        't_start': 9.972,
        'frame_duration': 0.02,
        'n_frames': 25,
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=0.85, |ω|=1.094 rad/s, dominant=ω_x
        'id': 'seg_B',
        't_start': 7.322,
        'frame_duration': 0.02,
        'n_frames': 25,
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=0.64, |ω|=0.794 rad/s, dominant=ω_y
        'id': 'seg_C',
        't_start': 4.422,
        'frame_duration': 0.02,
        'n_frames': 25,  
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=0.46, |ω|=0.574 rad/s, dominant=ω_y
        'id': 'seg_D',
        't_start': 1.922,
        'frame_duration': 0.02,
        'n_frames': 25,
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    ],
    # 'shapes_rotation' disabled:
    # 'shapes_rotation': [
    #     {  # quality=7.2, |ω|=0.757 rad/s
    #     'id': 'seg_A', 't_start': 2.416, 'frame_duration': 0.02,
    #     'n_frames': 25, 'initial_R': None, 'sensor_size': (180, 240)},
    #     {  # quality=7.2, |ω|=0.925 rad/s
    #     'id': 'seg_B', 't_start': 6.216, 'frame_duration': 0.02,
    #     'n_frames': 25, 'initial_R': None, 'sensor_size': (180, 240)},
    #     {  # quality=6.2, |ω|=0.646 rad/s
    #     'id': 'seg_C', 't_start': 1.616, 'frame_duration': 0.02,
    #     'n_frames': 25, 'initial_R': None, 'sensor_size': (180, 240)},
    #     {  # quality=1.2, |ω|=0.066 rad/s
    #     'id': 'seg_D', 't_start': 0.166, 'frame_duration': 0.02,
    #     'n_frames': 25, 'initial_R': None, 'sensor_size': (180, 240)},
    # ],
    'poster_rotation': [
           {  # quality=2.47, |ω|=2.816 rad/s, dominant=ω_z
        'id': 'seg_A',
        't_start': 14.166,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=1.77, |ω|=2.026 rad/s, dominant=ω_z
        'id': 'seg_B',
        't_start': 12.166,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=0.99, |ω|=1.123 rad/s, dominant=ω_x
        'id': 'seg_C',
        't_start': 8.816,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=0.60, |ω|=0.683 rad/s, dominant=ω_y
        'id': 'seg_D',
        't_start': 1.866,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=0.51, |ω|=0.575 rad/s, dominant=ω_y
        'id': 'seg_E',
        't_start': 5.066,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    ],
    'dynamic_rotation': [
    {  # quality=2.39, |ω|=2.618 rad/s, dominant=ω_z
        'id': 'seg_A',
        't_start': 11.769,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=2.27, |ω|=2.743 rad/s, dominant=ω_z
        'id': 'seg_B',
        't_start': 24.719,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=1.13, |ω|=1.436 rad/s, dominant=ω_y
        'id': 'seg_C',
        't_start': 31.919,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    {  # quality=0.82, |ω|=0.964 rad/s, dominant=ω_y
        'id': 'seg_D',
        't_start': 1.619,
        'frame_duration': 0.02,
        'n_frames': 150,  # 3.0s
        'initial_R': None,
        'sensor_size': (180, 240),
    },
    ],
    # Synthetic (ECRot, ESIM) — pinhole, clean steady GT. From convert_ecrot.py.
    # dt=10ms: fast rotation (~100 deg/s) => ~1 deg/frame, avoids intra-frame
    # motion blur in the reconstruction (20ms gives ~2 deg/frame and blurs).
    'bycicle_sinthetic': [
        {'id': 'seg_A', 't_start': 0.001, 'frame_duration': 0.01,
         'n_frames': 499, 'initial_R': None, 'sensor_size': (180, 240)},
    ],
}

# Backward-compatible: single config = first segment per dataset
DATASET_CONFIGS = {
    name: segs[0] for name, segs in DATASET_SEGMENTS.items()
}

# Adopted configuration — these are the values every result in the report uses.
#
# delta_FR and delta_IMU were changed from the values we started with
# (0.50 / 0.30) after the parameter sweep: lowering the kinematic weight and
# raising the anchor weight improved the error on all five sequences
# independently, most sharply on the synthetic ones (25.6 -> 7.2 deg/s). The
# sweep in the report varies each parameter from the ORIGINAL values, so the
# bold row there is 0.50 / 0.30, not the values below.
THESIS_PARAMS = dict(
    delta_VFG=0.12,    # OFCE, 0.15
    delta_IG=0.10,     # G from I: moderate
    delta_GI=0.05,     # I from G: gentle (Poisson step, needs stability)
    delta_RF=0.05,     # F from R: WEAK (let OFCE build local structure) 0.03
    delta_FR=0.10,     # R from F: was 0.50; lower = less magnitude shrinkage
    delta_IMU=0.50     # anchor weight: was 0.30; stronger is better throughout
)

COOK_PARAMS = dict(
    delta_VFG=0.08,
    delta_IG=0.12,
    delta_GI=0.08,
    delta_RF=0.03,  #0.10
    delta_FR=0.10,  # was 0.30; matched to THESIS_PARAMS so the two networks
                    # differ only in the update scheme, as the report requires
)

ITERS_PER_FRAME = 75   # Thesis use 50-75; 

# Distortion handling (ablation switch):
#   'undistort_events' : undistort events before binning; pinhole C    (original)
#   'C_full'           : raw events; distortion-aware coords + Jacobian in C  (best)
DISTORTION_MODE = 'C_full'

# Which of the thesis' two intensity updates recovers I from G:
#   'iterative' : Eq. 6.61, one Richardson step per iteration. Converges as
#                 (1 - delta_GI*|k|^2) per frequency, so at delta_GI=0.05 and
#                 75 iterations the low frequencies never form and I is an
#                 edge map.
#   'fft'       : Eq. 6.64-6.65, the exact frequency-domain solution. Periodic.
#   'dct'       : the same exact solve under Neumann boundaries (no wrap seam).
# Applies to the thesis network only; Cook's variant has its own I update.
POISSON_MODE = 'iterative'

# ---------------------------------------------------------------------------
# Helper: resolve paths for a dataset
# ---------------------------------------------------------------------------

def get_dataset_paths(dataset_name: str, base_dir: str = None):
    """Return a dict with all file paths for a given dataset."""
    if base_dir is None:
        base_dir = os.path.join(os.path.dirname(__file__), 'data')

    data_dir = os.path.join(base_dir, dataset_name)
    return {
        'data_dir': data_dir,
        'events': os.path.join(data_dir, 'events.txt'),
        'calib': os.path.join(data_dir, 'calib.txt'),
        'imu': os.path.join(data_dir, 'imu.txt'),
        'groundtruth': os.path.join(data_dir, 'groundtruth.txt'),
        # Exact angular velocity, written by convert_ecrot.py when the bag has a
        # twist topic (ECRot synthetic). Absent for the ECD sequences, whose
        # poses must be differenced instead. evaluation.py prefers it when present.
        'omega_gt': os.path.join(data_dir, 'omega_gt.txt'),
        'images': os.path.join(data_dir, 'images.txt'),

    }

def get_initial_R_from_imu(dataset_name: str):
    """Read the IMU gyroscope at t_start to get the correct initial_R."""
    cfg = DATASET_CONFIGS[dataset_name]
    paths = get_dataset_paths(dataset_name)
    
    imu_data = np.loadtxt(paths['imu'], dtype=np.float64)
    t_start = cfg['t_start']
    dt = cfg['frame_duration']
    
    # Find IMU readings closest to t_start
    t_lo = t_start
    t_hi = t_start + dt
    mask = (imu_data[:, 0] >= t_lo) & (imu_data[:, 0] < t_hi)
    
    if np.sum(mask) > 0:
        omega = np.mean(imu_data[mask, 4:7], axis=0)
    else:
        idx = np.argmin(np.abs(imu_data[:, 0] - t_start))
        omega = imu_data[idx, 4:7]
    
    return omega * dt  # rad/s → rad/frame