"""
Shared configuration for demo.py and validation.py.

Dataset configs are generated by find_segments.py.
Edit this file to add new datasets or change parameters.
"""

import os
import numpy as np

# ---------------------------------------------------------------------------
# Dataset Configurations (from find_segments.py)
# ---------------------------------------------------------------------------
# Per-dataset configurations (from find_segments.py output):
DATASET_CONFIGS = {
    'shapes_rotation': {
        't_start': 2.416,       
        'frame_duration': 0.020,
        'n_frames': 25,
        'initial_R':  np.array([0.00079, -0.01494, 0.00237]),
        'expected_omega': np.array([0.040, -0.747, 0.118]),
    },
    'boxes_rotation': {
        't_start': 10.872,
        'frame_duration': 0.020,
        'n_frames': 25,
        'initial_R': np.array([0.00308, 0.00203, -0.02959]),
        'expected_omega': np.array([0.154, 0.102, -1.479]),
    },
    'poster_rotation':{
        't_start':  8.816,
        'frame_duration': 0.020,
        'n_frames': 25,
        'initial_R': np.array([0.02242, 0.00101, 0.00055]),
        'expected_omega': np.array([1.121, 0.051, 0.027]),
    }
}

THESIS_PARAMS = dict(
        delta_VFG=0.20,    # OFCE: strong (must compete with kinematics) 0.15
        delta_IG=0.10,     # G from I: moderate
        delta_GI=0.05,     # I from G: gentle (Poisson step, needs stability)
        delta_RF=0.01,     # F from R: WEAK (let OFCE build local structure) 0.03
        delta_FR=0.80,     # R from F: strong (global aggregate, stable)  0.50
    )

COOK_PARAMS = dict(
    delta_VFG=0.08,
    delta_IG=0.12,
    delta_GI=0.08,
    delta_RF=0.10,
    delta_FR=0.50,
)

ITERS_PER_FRAME = 75

# ---------------------------------------------------------------------------
# Helper: resolve paths for a dataset
# ---------------------------------------------------------------------------

def get_dataset_paths(dataset_name: str, base_dir: str = None):
    """Return a dict with all file paths for a given dataset."""
    if base_dir is None:
        base_dir = os.path.join(os.path.dirname(__file__), 'data')

    data_dir = os.path.join(base_dir, dataset_name)
    return {
        'data_dir': data_dir,
        'events': os.path.join(data_dir, 'events.txt'),
        'calib': os.path.join(data_dir, 'calib.txt'),
        'imu': os.path.join(data_dir, 'imu.txt'),
        'groundtruth': os.path.join(data_dir, 'groundtruth.txt'),
    }